### ISSUE TITLE
UnboundLocalError: local variable 'end' referenced before assignment

### ISSUE THREAD

**Issue by jpcaruana** [HowFast/apm-python#14]
I had this issue in my sentry:

```python
UnboundLocalError
local variable 'end' referenced before assignment
```

<img width="815" alt="image" src="https://user-images.githubusercontent.com/31649/79234203-3b9d0200-7e6a-11ea-845e-9fad80429a8d.png">

We use `howfast-apm==0.6.0`

**Comment by MickaelBergem** [comment]
Thanks for reporting @jpcaruana, this is much appreciated!

This issue seems weird, I will look into it in the next few days.

**Comment by jpcaruana** [comment]
@MickaelBergem I will propose a fix soon :)

**Comment by MickaelBergem** [comment]
@jpcaruana thanks a lot for reporting! Version 0.6.1 is now live with this fix: https://pypi.org/project/howfast-apm/

I hope your apps don't raise too many `SystemExit` though ;)

**Comment by jpcaruana** [comment]
Sh*i happens :)

yes, we have work to do with these (few) `SystemExit`

Thanks for the review/fix/release !
